nelmio_api_doc:
    documentation:
        info:
            title: Eco Bliss Bath
            description: Documentation de l'API
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/(?!api/doc|_error/(.*)$) # Accepts routes under /api except /api/doc
